---
#Deployment API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peso-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peso-web
  template:
    metadata:
      labels:
        app: peso-web
    spec:
      containers:
        - name: peso-web
          image: na1jefferson/conversao-peso:v1
          ports:
            - containerPort: 80
---
# Service do peso-web
apiVersion: v1
kind: Service
metadata:
  name: peso-web
spec:
  selector:
    app: peso-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer